### ISSUE TITLE
Desktop Error : AnimateDiff Broken. 

### ISSUE THREAD

**Issue by Maki9009** [Skquark/AI-Friends#8]
tried to generate a vid, i didnt use any controlnet parameters 

Cloning into 'animatediff-cli-prompt-travel'...
remote: Enumerating objects: 870, done.
remote: Counting objects: 100% (299/299), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 870 (delta 264), reused 240 (delta 232), pack-reused 571
Receiving objects: 100% (870/870), 1.84 MiB | 2.39 MiB/s, done.
Resolving deltas: 100% (521/521), done.
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Program Files (x86)\\StableDiffusionDeluxe\\venv\\Lib\\site-packages\\cv2\\cv2.pyd'
Check the permissions.

WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
  WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\program files (x86)\stablediffusiondeluxe\venv\lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
copier 8.2.0 requires pydantic>=2.0.3, but you have pydantic 1.10.12 which is incompatible.
Exception in thread Thread-409 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\StableDiffusionDeluxe\venv\Stable-Diffusion-Deluxe.py", line 9737, in <lambda>
    ElevatedButton(content=Text("💚  Run AnimateDiff", size=20), color=colors.ON_PRIMARY_CONTAINER, bgcolor=colors.PRIMARY_CONTAINER, height=45, on_click=lambda _: run_animate_diff(page)),
  File "C:\Program Files (x86)\StableDiffusionDeluxe\venv\Stable-Diffusion-Deluxe.py", line 30968, in run_animate_diff
    run_sp(f"rm -rf {sd_models}", realtime=False)
  File "C:\Program Files (x86)\StableDiffusionDeluxe\venv\Stable-Diffusion-Deluxe.py", line 51, in run_sp
    return subprocess.run(cmd_list, stdout=subprocess.PIPE, env=env).stdout.decode('utf-8')
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\mahmo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Maki9009** [comment]
the GUI still says its installing animatediff lol

**Comment by Skquark** [comment]
Trying to decipher that error message.  For the first one "Access is denied: '...\cv2\cv2.pyd' Check the permissions." can really only mean one thing, that you're not launching the app as an Administrator.  Is it possible your antivirus blocked or disinfected the bat file? That could explain the other problem you were having too. When you run the script from shortcut, do you get the window asking to run as administrator? I hope that's the reason, because I can't think of another fix for that one simply running opencv.. 
The error "copier 8.2.0 requires pydantic>=2.0.3", but in the animatediff setup it's specifying "pydantic >= 1.10.0, < 2.0.0", I'm not installing copier explicitly. I hate version conflicts that I have no control over, maybe I can install copier==8.1.0 before pydantic and it'll accept. I don't know difference and it works in Colab, but will see what I can do.
Next error was running "rm -rf {sd_models}", which was a step in the original AnimateDiff install which I can probably just comment out or replace with shutil.rmtree(sd_models), but not sure why we're removing the folder there.  
I'll commit those little fixes later, hope it'll make a difference.  Thanks for your patience...

**Comment by Skquark** [comment]
Those errors should be all fixed, hopefully all's good.  Please let me know if you're still getting errors with it while using in Desktop.  Thanks...
